# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PPConverter
                                 A QGIS plugin
 Plugin to convert files created with Photoplan
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-03
        copyright            : (C) 2019 by Nils Müller-Scheeßel
        email                : mueller-scheessel@gmx.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ppconverter class from file ppconverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ppconverter import ppconverter
    return ppconverter(iface)