######################################################################
# Automatically generated by qmake (2.01a) Fr. Apr 12 18:08:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . i18n
INCLUDEPATH += .

# Input
FORMS += ui_ppconverter.ui
RESOURCES += resources.qrc
TRANSLATIONS += i18n/ppconverter_de_DE.ts
